services:
    app:
        container_name: "${CONTAINER_NAME_SERVICE}"
        image: "${COMPOSE_PROJECT_NAME}:latest"
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "${APP_PORT}:80"
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            sql:
                condition: service_healthy
    sql:
        container_name: ${CONTAINER_NAME_SQL}
        image: mysql:8.0
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}" ]
            interval: 5s
            timeout: 10s
            retries: 10
    frontend:
        container_name: "${VITE_APP_NAME}"
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.frontend
        volumes:
            - ./frontend:/app:delegated
            - node_modules_volume:/app/node_modules
        ports:
            - "${VITE_PORT}:3000"
volumes:
    db_data:
    node_modules_volume:
